.division <- structure(list(code = c("01", 
    "02", "07", "08", "09", "10", 
    "12", "13", "14", "15", "16", 
    "17", "20", "21", "22", "23", 
    "24", "25", "26", "27", "28", 
    "29", "30", "31", "32", "33", 
    "34", "35", "36", "37", "38", 
    "39", "40", "41", "42", "43", 
    "44", "45", "46", "47", "48", 
    "49", "50", "51", "52", "53", 
    "54", "55", "56", "57", "58", 
    "59", "60", "61", "62", "63", 
    "64", "65", "67", "70", "72", 
    "73", "75", "76", "78", "79", 
    "80", "81", "82", "83", "84", 
    "86", "87", "88", "89", "91", 
    "92", "93", "94", "95", "96", 
    "97", "99"), description = c("A Agriculture, Forestry, And Fishing", 
    "A Agriculture, Forestry, And Fishing", 
    "A Agriculture, Forestry, And Fishing", 
    "A Agriculture, Forestry, And Fishing", 
    "A Agriculture, Forestry, And Fishing", 
    "B Mining", "B Mining", "B Mining", 
    "B Mining", "C Construction", 
    "C Construction", "C Construction", 
    "D Manufacturing", "D Manufacturing", 
    "D Manufacturing", "D Manufacturing", 
    "D Manufacturing", "D Manufacturing", 
    "D Manufacturing", "D Manufacturing", 
    "D Manufacturing", "D Manufacturing", 
    "D Manufacturing", "D Manufacturing", 
    "D Manufacturing", "D Manufacturing", 
    "D Manufacturing", "D Manufacturing", 
    "D Manufacturing", "D Manufacturing", 
    "D Manufacturing", "D Manufacturing", 
    "E Transportation, Communications, Electric, Gas, And Sanitary Services", 
    "E Transportation, Communications, Electric, Gas, And Sanitary Services", 
    "E Transportation, Communications, Electric, Gas, And Sanitary Services", 
    "E Transportation, Communications, Electric, Gas, And Sanitary Services", 
    "E Transportation, Communications, Electric, Gas, And Sanitary Services", 
    "E Transportation, Communications, Electric, Gas, And Sanitary Services", 
    "E Transportation, Communications, Electric, Gas, And Sanitary Services", 
    "E Transportation, Communications, Electric, Gas, And Sanitary Services", 
    "E Transportation, Communications, Electric, Gas, And Sanitary Services", 
    "E Transportation, Communications, Electric, Gas, And Sanitary Services", 
    "F Wholesale Trade", "F Wholesale Trade", 
    "G Retail Trade", "G Retail Trade", 
    "G Retail Trade", "G Retail Trade", 
    "G Retail Trade", "G Retail Trade", 
    "G Retail Trade", "G Retail Trade", 
    "H Finance, Insurance, And Real Estate", 
    "H Finance, Insurance, And Real Estate", 
    "H Finance, Insurance, And Real Estate", 
    "H Finance, Insurance, And Real Estate", 
    "H Finance, Insurance, And Real Estate", 
    "H Finance, Insurance, And Real Estate", 
    "H Finance, Insurance, And Real Estate", 
    "I Services", "I Services", 
    "I Services", "I Services", 
    "I Services", "I Services", 
    "I Services", "I Services", 
    "I Services", "I Services", 
    "I Services", "I Services", 
    "I Services", "I Services", 
    "I Services", "I Services", 
    "J Public Administration", 
    "J Public Administration", 
    "J Public Administration", 
    "J Public Administration", 
    "J Public Administration", 
    "J Public Administration", 
    "J Public Administration", 
    "J Public Administration")), 
    row.names = c(NA, -83L), class = "data.frame")
.major_group <- structure(list(code = c("01", 
    "02", "07", "08", "09", "10", 
    "12", "13", "14", "15", "16", 
    "17", "20", "21", "22", "23", 
    "24", "25", "26", "27", "28", 
    "29", "30", "31", "32", "33", 
    "34", "35", "36", "37", "38", 
    "39", "40", "41", "42", "43", 
    "44", "45", "46", "47", "48", 
    "49", "50", "51", "52", "53", 
    "54", "55", "56", "57", "58", 
    "59", "60", "61", "62", "63", 
    "64", "65", "67", "70", "72", 
    "73", "75", "76", "78", "79", 
    "80", "81", "82", "83", "84", 
    "86", "87", "88", "89", "91", 
    "92", "93", "94", "95", "96", 
    "97", "99"), description = c("Agricultural Production Crops", 
    "Agriculture production livestock and animal specialties", 
    "Agricultural Services", "Forestry", 
    "Fishing, hunting, and trapping", 
    "Metal Mining", "Coal Mining", 
    "Oil And Gas Extraction", "Mining And Quarrying Of Nonmetallic Minerals, Except Fuels", 
    "Building Construction General Contractors And Operative Builders", 
    "Heavy Construction Other Than Building Construction Contractors", 
    "Construction Special Trade Contractors", 
    "Food And Kindred Products", 
    "Tobacco Products", "Textile Mill Products", 
    "Apparel And Other Finished Products Made From Fabrics And Similar Materials", 
    "Lumber And Wood Products, Except Furniture", 
    "Furniture And Fixtures", "Paper And Allied Products", 
    "Printing, Publishing, And Allied Industries", 
    "Chemicals And Allied Products", 
    "Petroleum Refining And Related Industries", 
    "Rubber And Miscellaneous Plastics Products", 
    "Leather And Leather Products", 
    "Stone, Clay, Glass, And Concrete Products", 
    "Primary Metal Industries", 
    "Fabricated Metal Products, Except Machinery And Transportation Equipment", 
    "Industrial And Commercial Machinery And Computer Equipment", 
    "Electronic And Other Electrical Equipment And Components, Except Computer Equipment", 
    "Transportation Equipment", 
    "Measuring, Analyzing, And Controlling Instruments; Photographic, Medical And Optical Goods; Watches And Clocks", 
    "Miscellaneous Manufacturing Industries", 
    "Railroad Transportation", 
    "Local And Suburban Transit And Interurban Highway Passenger Transportation", 
    "Motor Freight Transportation And Warehousing", 
    "United States Postal Service", 
    "Water Transportation", "Transportation By Air", 
    "Pipelines, Except Natural Gas", 
    "Transportation Services", 
    "Communications", "Electric, Gas, And Sanitary Services", 
    "Wholesale Trade-durable Goods", 
    "Wholesale Trade-non-durable Goods", 
    "Building Materials, Hardware, Garden Supply, And Mobile Home Dealers", 
    "General Merchandise Stores", 
    "Food Stores", "Automotive Dealers And Gasoline Service Stations", 
    "Apparel And Accessory Stores", 
    "Home Furniture, Furnishings, And Equipment Stores", 
    "Eating And Drinking Places", 
    "Miscellaneous Retail", "Depository Institutions", 
    "Non-depository Credit Institutions", 
    "Security And Commodity Brokers, Dealers, Exchanges, And Services", 
    "Insurance Carriers", "Insurance Agents, Brokers, And Service", 
    "Real Estate", "Holding And Other Investment Offices", 
    "Hotels, Rooming Houses, Camps, And Other Lodging Places", 
    "Personal Services", "Business Services", 
    "Automotive Repair, Services, And Parking", 
    "Miscellaneous Repair Services", 
    "Motion Pictures", "Amusement And Recreation Services", 
    "Health Services", "Legal Services", 
    "Educational Services", "Social Services", 
    "Museums, Art Galleries, And Botanical And Zoological Gardens", 
    "Membership Organizations", 
    "Engineering, Accounting, Research, Management, And Related Services", 
    "Private Households", "Miscellaneous Services", 
    "Executive, Legislative, And General Government, Except Finance", 
    "Justice, Public Order, And Safety", 
    "Public Finance, Taxation, And Monetary Policy", 
    "Administration Of Human Resource Programs", 
    "Administration Of Environmental Quality And Housing Programs", 
    "Administration Of Economic Programs", 
    "National Security And International Affairs", 
    "Nonclassifiable Establishments")), 
    row.names = c(NA, -83L), class = "data.frame")
.industry_group <- structure(list(code = c("011", 
    "013", "016", "017", "018", 
    "019", "021", "024", "025", 
    "027", "029", "071", "072", 
    "074", "075", "076", "078", 
    "081", "083", "085", "091", 
    "092", "097", "101", "102", 
    "103", "104", "106", "108", 
    "109", "122", "123", "124", 
    "131", "132", "138", "141", 
    "142", "144", "145", "147", 
    "148", "149", "152", "153", 
    "154", "161", "162", "171", 
    "172", "173", "174", "175", 
    "176", "177", "178", "179", 
    "201", "202", "203", "204", 
    "205", "206", "207", "208", 
    "209", "211", "212", "213", 
    "214", "221", "222", "223", 
    "224", "225", "226", "227", 
    "228", "229", "231", "232", 
    "233", "234", "235", "236", 
    "237", "238", "239", "241", 
    "242", "243", "244", "245", 
    "249", "251", "252", "253", 
    "254", "259", "261", "262", 
    "263", "265", "267", "271", 
    "272", "273", "274", "275", 
    "276", "277", "278", "279", 
    "281", "282", "283", "284", 
    "285", "286", "287", "289", 
    "291", "295", "299", "301", 
    "302", "305", "306", "308", 
    "311", "313", "314", "315", 
    "316", "317", "319", "321", 
    "322", "323", "324", "325", 
    "326", "327", "328", "329", 
    "331", "332", "333", "334", 
    "335", "336", "339", "341", 
    "342", "343", "344", "345", 
    "346", "347", "348", "349", 
    "351", "352", "353", "354", 
    "355", "356", "357", "358", 
    "359", "361", "362", "363", 
    "364", "365", "366", "367", 
    "369", "371", "372", "373", 
    "374", "375", "376", "379", 
    "381", "382", "384", "385", 
    "386", "387", "391", "393", 
    "394", "395", "396", "399", 
    "401", "411", "412", "413", 
    "414", "415", "417", "421", 
    "422", "423", "431", "441", 
    "442", "443", "444", "448", 
    "449", "451", "452", "458", 
    "461", "472", "473", "474", 
    "478", "481", "482", "483", 
    "484", "489", "491", "492", 
    "493", "494", "495", "496", 
    "497", "501", "502", "503", 
    "504", "505", "506", "507", 
    "508", "509", "511", "512", 
    "513", "514", "515", "516", 
    "517", "518", "519", "521", 
    "523", "525", "526", "527", 
    "531", "533", "539", "541", 
    "542", "543", "544", "545", 
    "546", "549", "551", "552", 
    "553", "554", "555", "556", 
    "557", "559", "561", "562", 
    "563", "564", "565", "566", 
    "569", "571", "572", "573", 
    "581", "591", "592", "593", 
    "594", "596", "598", "599", 
    "601", "602", "603", "606", 
    "608", "609", "611", "614", 
    "615", "616", "621", "622", 
    "623", "628", "631", "632", 
    "633", "635", "636", "637", 
    "639", "641", "651", "653", 
    "654", "655", "671", "672", 
    "673", "679", "701", "702", 
    "703", "704", "721", "722", 
    "723", "724", "725", "726", 
    "729", "731", "732", "733", 
    "734", "735", "736", "737", 
    "738", "751", "752", "753", 
    "754", "762", "763", "764", 
    "769", "781", "782", "783", 
    "784", "791", "792", "793", 
    "794", "799", "801", "802", 
    "803", "804", "805", "806", 
    "807", "808", "809", "811", 
    "821", "822", "823", "824", 
    "829", "832", "833", "835", 
    "836", "839", "841", "842", 
    "861", "862", "863", "864", 
    "865", "866", "869", "871", 
    "872", "873", "874", "881", 
    "899", "911", "912", "913", 
    "919", "921", "922", "931", 
    "941", "943", "944", "945", 
    "951", "953", "961", "962", 
    "963", "964", "965", "966", 
    "971", "972", "999"), description = c("Cash Grains", 
    "Field Crops, Except Cash Grains", 
    "Vegetables And Melons", "Fruits And Tree Nuts", 
    "Horticultural Specialties", 
    "General Farms, Primarily Crop", 
    "Livestock, Except Dairy And Poultry", 
    "Dairy Farms", "Poultry And Eggs", 
    "Animal Specialties", "General Farms, Primarily Livestock and Animal Specialties", 
    "Soil Preparation Services", 
    "Crop Services", "Veterinary Services", 
    "Animal Services, Except Veterinary", 
    "Farm Labor And Management Services", 
    "Landscape And Horticultural Services", 
    "Timber Tracts", "Forest Nurseries And Gathering Of Forest", 
    "Forestry Services", "Commercial Fishing", 
    "Fish Hatcheries And Preserves", 
    "Hunting And Trapping, And Game Propagation", 
    "Iron Ores", "Copper Ores", 
    "Lead And Zinc Ores", "Gold And Silver Ores", 
    "Ferroalloy Ores, Except Vanadium", 
    "Metal Mining Services", "Miscellaneous Metal Ores", 
    "Bituminous Coal And Lignite Mining", 
    "Anthracite Mining", "Coal Mining Services", 
    "Crude Petroleum And Natural Gas", 
    "Natural Gas Liquids", "Oil And Gas Field Services", 
    "Dimension Stone", "Crushed And Broken Stone, Including Riprap", 
    "Sand And Gravel", "Clay, Ceramic, And Refractory Minerals", 
    "Chemical And Fertilizer Mineral Mining", 
    "Nonmetallic Minerals Services, Except Fuels", 
    "Miscellaneous Nonmetallic Minerals, Except", 
    "General Building Contractors-residential", 
    "Operative Builders", "General Building Contractors-nonresidential", 
    "Highway And Street Construction, Except", 
    "Heavy Construction, Except Highway And Street", 
    "Plumbing, Heating And Air-conditioning", 
    "Painting And Paper Hanging", 
    "Electrical Work", "Masonry, Stonework, Tile Setting, And Plastering", 
    "Carpentry And Floor Work", 
    "Roofing, Siding, And Sheet Metal Work", 
    "Concrete Work", "Water Well Drilling", 
    "Miscellaneous Special Trade Contractors", 
    "Meat Products", "Dairy Products", 
    "Canned, Frozen, And Preserved Fruits, Vegetables, and Food Specialties", 
    "Grain Mill Products", "Bakery Products", 
    "Sugar And Confectionery Products", 
    "Fats And Oils", "Beverages", 
    "Miscellaneous Food Preparations And Kindred", 
    "Cigarettes", "Cigars", "Chewing And Smoking Tobacco And Snuff", 
    "Tobacco Stemming And Redrying", 
    "Broadwoven Fabric Mills, Cotton", 
    "Broadwoven Fabric Mills, Manmade Fiber And Silk", 
    "Broadwoven Fabric Mills, Wool (including Dyeing and Finishing)", 
    "Narrow Fabric And Other Smallwares Mills, Cotton, Wool, Silk, and Manmade Fiber", 
    "Knitting Mills", "Dyeing And Finishing Textiles, Except Wool Fabrics", 
    "Carpets And Rugs", "Yarn And Thread Mills", 
    "Miscellaneous Textile Goods", 
    "Men's And Boys' Suits, Coats, And Overcoats", 
    "Men's And Boys' Furnishings, Work Clothing, And Allied Garments", 
    "Women's, Misses', And Juniors' Outerwear", 
    "Women's, Misses', Children's, And Infants'", 
    "Hats, Caps, And Millinery", 
    "Girls', Children's, And Infants' Outerwear", 
    "Fur Goods", "Miscellaneous Apparel And Accessories", 
    "Miscellaneous Fabricated Textile Products", 
    "Logging", "Sawmills And Planing Mills", 
    "Millwork, Veneer, Plywood, And Structural Wood", 
    "Wood Containers", "Wood Buildings And Mobile Homes", 
    "Miscellaneous Wood Products", 
    "Household Furniture", "Office Furniture", 
    "Public Building And Related Furniture", 
    "Partitions, Shelving, Lockers, And Office And", 
    "Miscellaneous Furniture And Fixtures", 
    "Pulp Mills", "Paper Mills", 
    "Paperboard Mills", "Paperboard Containers And Boxes", 
    "Converted Paper And Paperboard Products, Except", 
    "Newspapers: Publishing, Or Publishing And Printing", 
    "Periodicals: Publishing, Or Publishing And Printing", 
    "Books", "Miscellaneous Publishing", 
    "Commercial Printing", "Manifold Business Forms", 
    "Greeting Cards", "Blankbooks, Looseleaf Binders, And Bookbinding", 
    "Service Industries For The Printing Trade", 
    "Industrial Inorganic Chemicals", 
    "Plastics Materials And Synthetic Resins, Synthetic", 
    "Drugs", "Soap, Detergents, And Cleaning Preparations; Perfumes, Cosmetics, and Other Toilet Preparations", 
    "Paints, Varnishes, Lacquers, Enamels, And Allied", 
    "Industrial Organic Chemicals", 
    "Agricultural Chemicals", "Miscellaneous Chemical Products", 
    "Petroleum Refining", "Asphalt Paving And Roofing Materials", 
    "Miscellaneous Products Of Petroleum And Coal", 
    "Tires And Inner Tubes", "Rubber And Plastics Footwear", 
    "Gaskets, Packing, And Sealing Devices And Rubber", 
    "Fabricated Rubber Products, Not Elsewhere", 
    "Miscellaneous Plastics Products", 
    "Leather Tanning And Finishing", 
    "Boot And Shoe Cut Stock And Findings", 
    "Footwear, Except Rubber", 
    "Leather Gloves And Mittens", 
    "Luggage", "Handbags And Other Personal Leather Goods", 
    "Leather Goods, Not Elsewhere Classified", 
    "Flat Glass", "Glass And Glassware, Pressed Or Blown", 
    "Glass Products, Made Of Purchased Glass", 
    "Cement, Hydraulic", "Structural Clay Products", 
    "Pottery And Related Products", 
    "Concrete, Gypsum, And Plaster Products", 
    "Cut Stone And Stone Products", 
    "Abrasive, Asbestos, And Miscellaneous", 
    "Steel Works, Blast Furnaces, And Rolling And Finishing Mills", 
    "Iron And Steel Foundries", 
    "Primary Smelting And Refining Of Nonferrous", 
    "Secondary Smelting And Refining Of Nonferrous", 
    "Rolling, Drawing, And Extruding Of Nonferrous", 
    "Nonferrous Foundries (castings)", 
    "Miscellaneous Primary Metal Products", 
    "Metal Cans And Shipping Containers", 
    "Cutlery, Handtools, And General Hardware", 
    "Heating Equipment, Except Electric And Warm Air;", 
    "Fabricated Structural Metal Products", 
    "Screw Machine Products, And Bolts, Nuts, Screws, Rivets, And Washers", 
    "Metal Forgings And Stampings", 
    "Coating, Engraving, And Allied Services", 
    "Ordnance And Accessories, Except Vehicles And Guided Missiles", 
    "Miscellaneous Fabricated Metal Products", 
    "Engines And Turbines", "Farm And Garden Machinery And Equipment", 
    "Construction, Mining, And Materials Handling", 
    "Metalworking Machinery And Equipment", 
    "Special Industry Machinery, Except Metalworking", 
    "General Industrial Machinery And Equipment", 
    "Computer And Office Equipment", 
    "Refrigeration And Service Industry Machinery", 
    "Miscellaneous Industrial And Commercial", 
    "Electric Transmission And Distribution Equipment", 
    "Electrical Industrial Apparatus", 
    "Household Appliances", "Electric Lighting And Wiring Equipment", 
    "Household Audio And Video Equipment, And Audio", 
    "Communications Equipment", 
    "Electronic Components And Accessories", 
    "Miscellaneous Electrical Machinery, Equipment, and Supplies", 
    "Motor Vehicles And Motor Vehicle Equipment", 
    "Aircraft And Parts", "Ship And Boat Building And Repairing", 
    "Railroad Equipment", "Motorcycles, Bicycles, And Parts", 
    "Guided Missiles And Space Vehicles And Parts", 
    "Miscellaneous Transportation Equipment", 
    "Search, Detection, Navigation, Guidance, Aeronautical, and Nautical Systems, Instruments, and Equipment", 
    "Laboratory Apparatus And Analytical, Optical, Measuring, and Controlling Instruments", 
    "Surgical, Medical, And Dental Instruments And Supplies", 
    "Ophthalmic Goods", "Photographic Equipment And Supplies", 
    "Watches, Clocks, Clockwork Operated Devices, and Parts", 
    "Jewelry, Silverware, And Plated Ware", 
    "Musical Instruments", "Dolls, Toys, Games And Sporting And Athletic", 
    "Pens, Pencils, And Other Artists Materials", 
    "Costume Jewelry, Costume Novelties, Buttons, And Miscellaneous Notions, Ecept Precious Metal", 
    "Miscellaneous Manufacturing Industries", 
    "Railroads", "Local And Suburban Passenger Transportation", 
    "Taxicabs", "Intercity And Rural Bus Transportation", 
    "Bus Charter Service", "School Buses", 
    "Terminal And Service Facilities For Motor Vehicle", 
    "Trucking And Courier Services, Except Air", 
    "Public Warehousing And Storage", 
    "Terminal And Joint Terminal Maintenance", 
    "United States Postal Service", 
    "Deep Sea Foreign Transportation Of Freight", 
    "Deep Sea Domestic Transportation Of Freight", 
    "Freight Transportation On The Great Lakes-st.", 
    "Water Transportation Of Freight, Not Elsewhere", 
    "Water Transportation Of Passengers", 
    "Services Incidental To Water Transportation", 
    "Air Transportation, Scheduled, And Air Courier", 
    "Air Transportation, Nonscheduled", 
    "Airports, Flying Fields, And Airport Terminal", 
    "Pipelines, Except Natural Gas", 
    "Arrangement Of Passenger Transportation", 
    "Arrangement Of Transportation Of Freight And Cargo", 
    "Rental Of Railroad Cars", 
    "Miscellaneous Services Incidental To Transportation", 
    "Telephone Communications", 
    "Telegraph And Other Message Communications", 
    "Radio And Television Broadcasting Stations", 
    "Cable And Other Pay Television Services", 
    "Communications Services, Not Elsewhere", 
    "Electric Services", "Gas Production And Distribution", 
    "Combination Electric And Gas, And Other Utility", 
    "Water Supply", "Sanitary Services", 
    "Steam And Air-conditioning Supply", 
    "Irrigation Systems", "Motor Vehicles And Motor Vehicle Parts And Supplies", 
    "Furniture And Home Furnishings", 
    "Lumber And Other Construction Materials", 
    "Professional And Commercial Equipment And Supplies", 
    "Metals And Minerals, Except Petroleum", 
    "Electrical Goods", "Hardware, And Plumbing And Heating Equipment", 
    "Machinery, Equipment, And Supplies", 
    "Miscellaneous Durable Goods", 
    "Paper And Paper Products", 
    "Drugs, Drug Proprietaries, And Druggists' Sundries", 
    "Apparel, Piece Goods, And Notions", 
    "Groceries And Related Products", 
    "Farm-product Raw Materials", 
    "Chemicals And Allied Products", 
    "Petroleum And Petroleum Products", 
    "Beer, Wine, And Distilled Alcoholic Beverages", 
    "Miscellaneous Non-durable Goods", 
    "Lumber And Other Building Materials Dealers", 
    "Paint, Glass And Wallpaper Stores", 
    "Hardware Stores", "Retail Nurseries, Lawn And Garden Supply Stores", 
    "Mobile Home Dealers", "Department Stores", 
    "Variety Stores", "Miscellaneous General Merchandise Stores", 
    "Grocery Stores", "Meat And Fish (seafood) Markets, Including", 
    "Fruit And Vegetable Markets", 
    "Candy, Nut, And Confectionery Stores", 
    "Dairy Products Stores", "Retail Bakeries", 
    "Miscellaneous Food Stores", 
    "Motor Vehicle Dealers (new And Used)", 
    "Motor Vehicle Dealers (used Only)", 
    "Auto And Home Supply Stores", 
    "Gasoline Service Stations", 
    "Boat Dealers", "Recreational Vehicle Dealers", 
    "Motorcycle Dealers", "Automotive Dealers, Not Elsewhere Classified", 
    "Men's And Boys' Clothing And Accessory Stores", 
    "Women's Clothing Stores", 
    "Women's Accessory And Specialty Stores", 
    "Children's And Infants' Wear Stores", 
    "Family Clothing Stores", "Shoe Stores", 
    "Miscellaneous Apparel And Accessory Stores", 
    "Home Furniture And Furnishings Stores", 
    "Household Appliance Stores", 
    "Radio, Television, Consumer Electronics, And Music Stores", 
    "Eating And Drinking Places", 
    "Drug Stores And Proprietary Stores", 
    "Liquor Stores", "Used Merchandise Stores", 
    "Miscellaneous Shopping Goods Stores", 
    "Nonstore Retailers", "Fuel Dealers", 
    "Retail Stores, Not Elsewhere Classified", 
    "Central Reserve Depository Institutions", 
    "Commercial Banks", "Savings Institutions", 
    "Credit Unions", "Foreign Banking And Branches And Agencies Of", 
    "Functions Related To Depository Banking", 
    "Federal And Federally-sponsored Credit Agencies", 
    "Personal Credit Institutions", 
    "Business Credit Institutions", 
    "Mortgage Bankers And Brokers", 
    "Security Brokers, Dealers, And Flotation", 
    "Commodity Contracts Brokers And Dealers", 
    "Security And Commodity Exchanges", 
    "Services Allied With The Exchange Of Securities", 
    "Life Insurance", "Accident And Health Insurance And Medical", 
    "Fire, Marine, And Casualty Insurance", 
    "Surety Insurance", "Title Insurance", 
    "Pension, Health, And Welfare Funds", 
    "Insurance Carriers, Not Elsewhere Classified", 
    "Insurance Agents, Brokers, And Service", 
    "Real Estate Operators (except Developers) And Lessors", 
    "Real Estate Agents And Managers", 
    "Title Abstract Offices", "Land Subdividers And Developers", 
    "Holding Offices", "Investment Offices", 
    "Trusts", "Miscellaneous Investing", 
    "Hotels And Motels", "Rooming And Boarding Houses", 
    "Camps And Recreational Vehicle Parks", 
    "Organization Hotels And Lodging Houses, On", 
    "Laundry, Cleaning, And Garment Services", 
    "Photographic Studios, Portrait", 
    "Beauty Shops", "Barber Shops", 
    "Shoe Repair Shops And Shoeshine Parlors", 
    "Funeral Service And Crematories", 
    "Miscellaneous Personal Services", 
    "Advertising", "Consumer Credit Reporting Agencies, Mercantile", 
    "Mailing, Reproduction, Commercial Art And Photography, and Stenographic Services", 
    "Services To Dwellings And Other Buildings", 
    "Miscellaneous Equipment Rental And Leasing", 
    "Personnel Supply Services", 
    "Computer Programming, Data Processing, And Other Computer Related Services", 
    "Miscellaneous Business Services", 
    "Automotive Rental And Leasing, Without Drivers", 
    "Automobile Parking", "Automotive Repair Shops", 
    "Automotive Services, Except Repair", 
    "Electrical Repair Shops", 
    "Watch, Clock, And Jewelry Repair", 
    "Reupholstery And Furniture Repair", 
    "Miscellaneous Repair Shops And Related Services", 
    "Motion Picture Production And Allied Services", 
    "Motion Picture Distribution And Allied Services", 
    "Motion Picture Theaters", 
    "Video Tape Rental", "Dance Studios, Schools, And Halls", 
    "Theatrical Producers (except Motion Picture),", 
    "Bowling Centers", "Commercial Sports", 
    "Miscellaneous Amusement And Recreation", 
    "Offices And Clinics Of Doctors Of Medicine", 
    "Offices And Clinics Of Dentists", 
    "Offices And Clinics Of Doctors Of Osteopathy", 
    "Offices And Clinics Of Other Health Practitioners", 
    "Nursing And Personal Care Facilities", 
    "Hospitals", "Medical And Dental Laboratories", 
    "Home Health Care Services", 
    "Miscellaneous Health And Allied Services, Not", 
    "Legal Services", "Elementary And Secondary Schools", 
    "Colleges, Universities, Professional Schools, And", 
    "Libraries", "Vocational Schools", 
    "Schools And Educational Services, Not Elsewhere", 
    "Individual And Family Social Services", 
    "Job Training And Vocational Rehabilitation", 
    "Child Day Care Services", 
    "Residential Care", "Social Services, Not Elsewhere Classified", 
    "Museums And Art Galleries", 
    "Arboreta And Botanical Or Zoological Gardens", 
    "Business Associations", "Professional Membership Organizations", 
    "Labor Unions And Similar Labor Organizations", 
    "Civic, Social, And Fraternal Associations", 
    "Political Organizations", 
    "Religious Organizations", 
    "Membership Organizations, Not Elsewhere", 
    "Engineering, Architectural, And Surveying", 
    "Accounting, Auditing, And Bookkeeping Services", 
    "Research, Development, And Testing Services", 
    "Management And Public Relations Services", 
    "Private Households", "Miscellaneous Services", 
    "Executive Offices", "Legislative Bodies", 
    "Executive And Legislative Offices Combined", 
    "General Government, Not Elsewhere Classified", 
    "Courts", "Public Order And Safety", 
    "Public Finance, Taxation, And Monetary Policy", 
    "Administration Of Educational Programs", 
    "Administration Of Public Health Programs", 
    "Administration Of Social, Human Resource And", 
    "Administration Of Veteran's Affairs, Except", 
    "Administration Of Environmental Quality", 
    "Administration Of Housing And Urban", 
    "Administration Of General Economic Programs", 
    "Regulation And Administration Of Transportation", 
    "Regulation And Administration Of", 
    "Regulation Of Agricultural Marketing And", 
    "Regulation, Licensing, And Inspection Of", 
    "Space Research And Technology", 
    "National Security", "International Affairs", 
    "Nonclassifiable Establishments")), 
    row.names = c(NA, -416L), class = "data.frame")
.industry <- structure(list(code = c("0111", 
    "0112", "0115", "0116", "0119", 
    "0131", "0132", "0133", "0134", 
    "0139", "0161", "0171", "0172", 
    "0173", "0174", "0175", "0179", 
    "0181", "0182", "0191", "0211", 
    "0212", "0213", "0214", "0219", 
    "0241", "0251", "0252", "0253", 
    "0254", "0259", "0271", "0272", 
    "0273", "0279", "0291", "0711", 
    "0721", "0722", "0723", "0724", 
    "0741", "0742", "0751", "0752", 
    "0761", "0762", "0781", "0782", 
    "0783", "0811", "0831", "0851", 
    "0912", "0913", "0919", "0921", 
    "0971", "1011", "1021", "1031", 
    "1041", "1044", "1061", "1081", 
    "1094", "1099", "1221", "1222", 
    "1231", "1241", "1311", "1321", 
    "1381", "1382", "1389", "1411", 
    "1422", "1423", "1429", "1442", 
    "1446", "1455", "1459", "1474", 
    "1475", "1479", "1481", "1499", 
    "1521", "1522", "1531", "1541", 
    "1542", "1611", "1622", "1623", 
    "1629", "1711", "1721", "1731", 
    "1741", "1742", "1743", "1751", 
    "1752", "1761", "1771", "1781", 
    "1791", "1793", "1794", "1795", 
    "1796", "1799", "2011", "2013", 
    "2015", "2021", "2022", "2023", 
    "2024", "2026", "2032", "2033", 
    "2034", "2035", "2037", "2038", 
    "2041", "2043", "2044", "2045", 
    "2046", "2047", "2048", "2051", 
    "2052", "2053", "2061", "2062", 
    "2063", "2064", "2066", "2067", 
    "2068", "2074", "2075", "2076", 
    "2077", "2079", "2082", "2083", 
    "2084", "2085", "2086", "2087", 
    "2091", "2092", "2095", "2096", 
    "2097", "2098", "2099", "2111", 
    "2121", "2131", "2141", "2211", 
    "2221", "2231", "2241", "2251", 
    "2252", "2253", "2254", "2257", 
    "2258", "2259", "2261", "2262", 
    "2269", "2273", "2281", "2282", 
    "2284", "2295", "2296", "2297", 
    "2298", "2299", "2311", "2321", 
    "2322", "2323", "2325", "2326", 
    "2329", "2331", "2335", "2337", 
    "2339", "2341", "2342", "2353", 
    "2361", "2369", "2371", "2381", 
    "2384", "2385", "2386", "2387", 
    "2389", "2391", "2392", "2393", 
    "2394", "2395", "2396", "2397", 
    "2399", "2411", "2421", "2426", 
    "2429", "2431", "2434", "2435", 
    "2436", "2439", "2441", "2448", 
    "2449", "2451", "2452", "2491", 
    "2493", "2499", "2511", "2512", 
    "2514", "2515", "2517", "2519", 
    "2521", "2522", "2531", "2541", 
    "2542", "2591", "2599", "2611", 
    "2621", "2631", "2652", "2653", 
    "2655", "2656", "2657", "2671", 
    "2672", "2673", "2674", "2675", 
    "2676", "2677", "2678", "2679", 
    "2711", "2721", "2731", "2732", 
    "2741", "2752", "2754", "2759", 
    "2761", "2771", "2782", "2789", 
    "2791", "2796", "2812", "2813", 
    "2816", "2819", "2821", "2822", 
    "2823", "2824", "2833", "2834", 
    "2835", "2836", "2841", "2842", 
    "2843", "2844", "2851", "2861", 
    "2865", "2869", "2873", "2874", 
    "2875", "2879", "2891", "2892", 
    "2893", "2895", "2899", "2911", 
    "2951", "2952", "2992", "2999", 
    "3011", "3021", "3052", "3053", 
    "3061", "3069", "3081", "3082", 
    "3083", "3084", "3085", "3086", 
    "3087", "3088", "3089", "3111", 
    "3131", "3142", "3143", "3144", 
    "3149", "3151", "3161", "3171", 
    "3172", "3199", "3211", "3221", 
    "3229", "3231", "3241", "3251", 
    "3253", "3255", "3259", "3261", 
    "3262", "3263", "3264", "3269", 
    "3271", "3272", "3273", "3274", 
    "3275", "3281", "3291", "3292", 
    "3295", "3296", "3297", "3299", 
    "3312", "3313", "3315", "3316", 
    "3317", "3321", "3322", "3324", 
    "3325", "3331", "3334", "3339", 
    "3341", "3351", "3353", "3354", 
    "3355", "3356", "3357", "3363", 
    "3364", "3365", "3366", "3369", 
    "3398", "3399", "3411", "3412", 
    "3421", "3423", "3425", "3429", 
    "3431", "3432", "3433", "3441", 
    "3442", "3443", "3444", "3446", 
    "3448", "3449", "3451", "3452", 
    "3462", "3463", "3465", "3466", 
    "3469", "3471", "3479", "3482", 
    "3483", "3484", "3489", "3491", 
    "3492", "3493", "3494", "3495", 
    "3496", "3497", "3498", "3499", 
    "3511", "3519", "3523", "3524", 
    "3531", "3532", "3533", "3534", 
    "3535", "3536", "3537", "3541", 
    "3542", "3543", "3544", "3545", 
    "3546", "3547", "3548", "3549", 
    "3552", "3553", "3554", "3555", 
    "3556", "3559", "3561", "3562", 
    "3563", "3564", "3565", "3566", 
    "3567", "3568", "3569", "3571", 
    "3572", "3575", "3577", "3578", 
    "3579", "3581", "3582", "3585", 
    "3586", "3589", "3592", "3593", 
    "3594", "3596", "3599", "3612", 
    "3613", "3621", "3624", "3625", 
    "3629", "3631", "3632", "3633", 
    "3634", "3635", "3639", "3641", 
    "3643", "3644", "3645", "3646", 
    "3647", "3648", "3651", "3652", 
    "3661", "3663", "3669", "3671", 
    "3672", "3674", "3675", "3676", 
    "3677", "3678", "3679", "3691", 
    "3692", "3694", "3695", "3699", 
    "3711", "3713", "3714", "3715", 
    "3716", "3721", "3724", "3728", 
    "3731", "3732", "3743", "3751", 
    "3761", "3764", "3769", "3792", 
    "3795", "3799", "3812", "3821", 
    "3822", "3823", "3824", "3825", 
    "3826", "3827", "3829", "3841", 
    "3842", "3843", "3844", "3845", 
    "3851", "3861", "3873", "3911", 
    "3914", "3915", "3931", "3942", 
    "3944", "3949", "3951", "3952", 
    "3953", "3955", "3961", "3965", 
    "3991", "3993", "3995", "3996", 
    "3999", "4011", "4013", "4111", 
    "4119", "4121", "4131", "4141", 
    "4142", "4151", "4173", "4212", 
    "4213", "4214", "4215", "4221", 
    "4222", "4225", "4226", "4231", 
    "4311", "4412", "4424", "4432", 
    "4449", "4481", "4482", "4489", 
    "4491", "4492", "4493", "4499", 
    "4512", "4513", "4522", "4581", 
    "4612", "4613", "4619", "4724", 
    "4725", "4729", "4731", "4741", 
    "4783", "4785", "4789", "4812", 
    "4813", "4822", "4832", "4833", 
    "4841", "4899", "4911", "4922", 
    "4923", "4924", "4925", "4931", 
    "4932", "4939", "4941", "4952", 
    "4953", "4959", "4961", "4971", 
    "5012", "5013", "5014", "5015", 
    "5021", "5023", "5031", "5032", 
    "5033", "5039", "5043", "5044", 
    "5045", "5046", "5047", "5048", 
    "5049", "5051", "5052", "5063", 
    "5064", "5065", "5072", "5074", 
    "5075", "5078", "5082", "5083", 
    "5084", "5085", "5087", "5088", 
    "5091", "5092", "5093", "5094", 
    "5099", "5111", "5112", "5113", 
    "5122", "5131", "5136", "5137", 
    "5139", "5141", "5142", "5143", 
    "5144", "5145", "5146", "5147", 
    "5148", "5149", "5153", "5154", 
    "5159", "5162", "5169", "5171", 
    "5172", "5181", "5182", "5191", 
    "5192", "5193", "5194", "5198", 
    "5199", "5211", "5231", "5251", 
    "5261", "5271", "5311", "5331", 
    "5399", "5411", "5421", "5431", 
    "5441", "5451", "5461", "5499", 
    "5511", "5521", "5531", "5541", 
    "5551", "5561", "5571", "5599", 
    "5611", "5621", "5632", "5641", 
    "5651", "5661", "5699", "5712", 
    "5713", "5714", "5719", "5722", 
    "5731", "5734", "5735", "5736", 
    "5812", "5813", "5912", "5921", 
    "5932", "5941", "5942", "5943", 
    "5944", "5945", "5946", "5947", 
    "5948", "5949", "5961", "5962", 
    "5963", "5983", "5984", "5989", 
    "5992", "5993", "5994", "5995", 
    "5999", "6011", "6019", "6021", 
    "6022", "6029", "6035", "6036", 
    "6061", "6062", "6081", "6082", 
    "6091", "6099", "6111", "6141", 
    "6153", "6159", "6162", "6163", 
    "6211", "6221", "6231", "6282", 
    "6289", "6311", "6321", "6324", 
    "6331", "6351", "6361", "6371", 
    "6399", "6411", "6512", "6513", 
    "6514", "6515", "6517", "6519", 
    "6531", "6541", "6552", "6553", 
    "6712", "6719", "6722", "6726", 
    "6732", "6733", "6792", "6794", 
    "6798", "6799", "7011", "7021", 
    "7032", "7033", "7041", "7211", 
    "7212", "7213", "7215", "7216", 
    "7217", "7218", "7219", "7221", 
    "7231", "7241", "7251", "7261", 
    "7291", "7299", "7311", "7312", 
    "7313", "7319", "7322", "7323", 
    "7331", "7334", "7335", "7336", 
    "7338", "7342", "7349", "7352", 
    "7353", "7359", "7361", "7363", 
    "7371", "7372", "7373", "7374", 
    "7375", "7376", "7377", "7378", 
    "7379", "7381", "7382", "7383", 
    "7384", "7389", "7513", "7514", 
    "7515", "7519", "7521", "7532", 
    "7533", "7534", "7536", "7537", 
    "7538", "7539", "7542", "7549", 
    "7622", "7623", "7629", "7631", 
    "7641", "7692", "7694", "7699", 
    "7812", "7819", "7822", "7829", 
    "7832", "7833", "7841", "7911", 
    "7922", "7929", "7933", "7941", 
    "7948", "7991", "7992", "7993", 
    "7996", "7997", "7999", "8011", 
    "8021", "8031", "8041", "8042", 
    "8043", "8049", "8051", "8052", 
    "8059", "8062", "8063", "8069", 
    "8071", "8072", "8082", "8092", 
    "8093", "8099", "8111", "8211", 
    "8221", "8222", "8231", "8243", 
    "8244", "8249", "8299", "8322", 
    "8331", "8351", "8361", "8399", 
    "8412", "8422", "8611", "8621", 
    "8631", "8641", "8651", "8661", 
    "8699", "8711", "8712", "8713", 
    "8721", "8731", "8732", "8733", 
    "8734", "8741", "8742", "8743", 
    "8744", "8748", "8811", "8999", 
    "9111", "9121", "9131", "9199", 
    "9211", "9221", "9222", "9223", 
    "9224", "9229", "9311", "9411", 
    "9431", "9441", "9451", "9511", 
    "9512", "9531", "9532", "9611", 
    "9621", "9631", "9641", "9651", 
    "9661", "9711", "9721", "9999"), 
    description = c("Wheat", "Rice", 
        "Corn", "Soybeans", "Cash Grains, Not Elsewhere Classified", 
        "Cotton", "Tobacco", "Sugarcane and Sugar Beets", 
        "Irish Potatoes", "Field Crops, Except Cash Grains, Not Elsewhere Classified", 
        "Vegetables and Melons", 
        "Berry Crops", "Grapes", 
        "Tree Nuts", "Citrus Fruits", 
        "Deciduous Tree Fruits", 
        "Fruits and Tree Nuts, Not Elsewhere Classified", 
        "Ornamental Floriculture and Nursery Products", 
        "Food Crops Grown Under Cover", 
        "General Farms, Primarily Crop", 
        "Beef Cattle Feedlots", 
        "Beef Cattle, Except Feedlots", 
        "Hogs", "Sheep and Goats", 
        "General Livestock, Except Dairy and Poultry", 
        "Dairy Farms", "Broiler, Fryer, and Roaster Chickens", 
        "Chicken Eggs", "Turkeys and Turkey Eggs", 
        "Poultry Hatcheries", "Poultry and Eggs, Not Elsewhere Classified", 
        "Fur-Bearing Animals and Rabbits", 
        "Horses and Other Equines", 
        "Animal Aquaculture", "Animal Specialties, Not Elsewhere Classified", 
        "General Farms, Primarily Livestock and Animal Specialties", 
        "Soil Preparation Services", 
        "Crop Planting, Cultivating, and Protecting", 
        "Crop Harvesting, Primarily by Machine", 
        "Crop Preparation Services for Market, Except Cotton Ginning", 
        "Cotton Ginning", "Veterinary Services for Livestock", 
        "Veterinary Services for Animal Specialties", 
        "Livestock Services, Except Veterinary", 
        "Animal Specialty Services, Except Veterinary", 
        "Farm Labor Contractors and Crew Leaders", 
        "Farm Management Services", 
        "Landscape Counseling and Planning", 
        "Lawn and Garden Services", 
        "Ornamental Shrub and Tree Services", 
        "Timber Tracts", "Forest Nurseries and Gathering of Forest Products", 
        "Forestry Services", "Finfish", 
        "Shellfish", "Miscellaneous Marine Products", 
        "Fish Hatcheries and Preserves", 
        "Hunting and Trapping, and Game Propagation", 
        "Iron Ores", "Copper Ores", 
        "Lead and Zinc Ores", "Gold Ores", 
        "Silver Ores", "Ferroalloy Ores, Except Vanadium", 
        "Metal Mining Services", 
        "Uranium-Radium-Vanadium Ores", 
        "Miscellaneous Metal Ores, Not Elsewhere Classified", 
        "Bituminous Coal and Lignite Surface Mining", 
        "Bituminous Coal Underground Mining", 
        "Anthracite Mining", "Coal Mining Services", 
        "Crude Petroleum and Natural Gas", 
        "Natural Gas Liquids", 
        "Drilling Oil and Gas Wells", 
        "Oil and Gas Field Exploration Services", 
        "Oil and Gas Field Services, Not Elsewhere Classified", 
        "Dimension Stone", "Crushed and Broken Limestone", 
        "Crushed and Broken Granite", 
        "Crushed and Broken Stone, Not Elsewhere Classified", 
        "Construction Sand and Gravel", 
        "Industrial Sand", "Kaolin and Ball Clay", 
        "Clay, Ceramic, and Refractory Minerals, Not Elsewhere Classified", 
        "Potash, Soda, and Borate Minerals", 
        "Phosphate Rock", "Chemical and Fertilizer Mineral Mining, Not Elsewhere Classified", 
        "Nonmetallic Minerals Services, Except Fuels", 
        "Miscellaneous Nonmetallic Minerals, Except Fuels", 
        "General Contractors-Single-Family Houses", 
        "General Contractors-Residential Buildings, Other Than Single-Family", 
        "Operative Builders", "General Contractors-Industrial Buildings and Warehouses", 
        "General Contractors-Nonresidential Buildings, Other than Industrial Buildings and Warehouses", 
        "Highway and Street Construction, Except Elevated Highways", 
        "Bridge, Tunnel, and Elevated Highway Construction", 
        "Water, Sewer, Pipeline, and Communications and Power Line Construction", 
        "Heavy Construction, Not Elsewhere Classified", 
        "Plumbing, Heating and Air-Conditioning", 
        "Painting and Paper Hanging", 
        "Electrical Work", "Masonry, Stone Setting, and Other Stone Work", 
        "Plastering, Drywall, Acoustical, and Insulation Work", 
        "Terrazzo, Tile, Marble, and Mosaic Work", 
        "Carpentry Work", "Floor Laying and Other Floor Work, Not Elsewhere Classified", 
        "Roofing, Siding, and Sheet Metal Work", 
        "Concrete Work", "Water Well Drilling", 
        "Structural Steel Erection", 
        "Glass and Glazing Work", 
        "Excavation Work", "Wrecking and Demolition Work", 
        "Installation or Erection of Building Equipment, Not Elsewhere", 
        "Special Trade Contractors, Not Elsewhere Classified", 
        "Meat Packing Plants", 
        "Sausages and Other Prepared Meat Products", 
        "Poultry Slaughtering and Processing", 
        "Creamery Butter", "Natural, Processed, and Imitation Cheese", 
        "Dry, Condensed, and Evaporated Dairy Products", 
        "Ice Cream and Frozen Desserts", 
        "Fluid Milk", "Canned Specialties", 
        "Canned Fruits, Vegetables, Preserves, Jams, and Jellies", 
        "Dried and Dehydrated Fruits, Vegetables, and Soup Mixes", 
        "Pickled Fruits and Vegetables, Vegetable Sauces and Seasonings, and Salad Dressings", 
        "Frozen Fruits, Fruit Juices, and Vegetables", 
        "Frozen Specialties, Not Elsewhere Classified", 
        "Flour and Other Grain Mill Products", 
        "Cereal Breakfast Foods", 
        "Rice Milling", "Prepared Flour Mixes and Doughs", 
        "Wet Corn Milling", "Dog and Cat Food", 
        "Prepared Feed and Feed Ingredients for Animals and Fowls, Except Dogs and Cats", 
        "Bread and Other Bakery Products, Except Cookies and Crackers", 
        "Cookies and Crackers", 
        "Frozen Bakery Products, Except Bread", 
        "Cane Sugar, Except Refining", 
        "Cane Sugar Refining", 
        "Beet Sugar", "Candy and Other Confectionery Products", 
        "Chocolate and Cocoa Products", 
        "Chewing Gum", "Salted and Roasted Nuts and Seeds", 
        "Cottonseed Oil Mills", 
        "Soybean Oil Mills", "Vegetable Oil Mills, Except Corn, Cottonseed, and Soybean", 
        "Animal and Marine Fats and Oils", 
        "Shortening, Table Oils, Margarine, and Other Edible Fats and Oils, Not Elsewhere Classified", 
        "Malt Beverages", "Malt", 
        "Wines, Brandy, and Brandy Spirits", 
        "Distilled and Blended Liquors", 
        "Bottled and Canned Soft Drinks and Carbonated Waters", 
        "Flavoring Extracts and Flavoring Syrups, Not Elsewhere Classified", 
        "Canned and Cured Fish and Seafoods", 
        "Prepared Fresh or Frozen Fish and Seafoods", 
        "Roasted Coffee", "Potato Chips, Corn Chips, and Similar Snacks", 
        "Manufactured Ice", "Macaroni, Spaghetti, Vermicelli, and Noodles", 
        "Food Preparations, Not Elsewhere Classified", 
        "Cigarettes", "Cigars", 
        "Chewing and Smoking Tobacco and Snuff", 
        "Tobacco Stemming and Redrying", 
        "Broadwoven Fabric Mills, Cotton", 
        "Broadwoven Fabric Mills, Manmade Fiber and Silk", 
        "Broadwoven Fabric Mills, Wool (Including Dyeing and Finishing)", 
        "Narrow Fabric and Other Smallware Mills: Cotton, Wool, Silk, and Manmade Fiber", 
        "Women's Full-Length and Knee-Length Hosiery, Except Socks", 
        "Hosiery, Not Elsewhere Classified", 
        "Knit Outerwear Mills", 
        "Knit Underwear and Nightwear Mills", 
        "Weft Knit Fabric Mills", 
        "Lace and Warp Knit Fabric Mills", 
        "Knitting Mills, Not Elsewhere Classified", 
        "Finishers of Broadwoven Fabrics of Cotton", 
        "Finishers of Broadwoven Fabrics of Manmade Fiber and Silk", 
        "Finishers of Textiles, Not elsewhere Classified", 
        "Carpets and Rugs", "Yarn Spinning Mills", 
        "Yarn Texturizing, Throwing, Twisting, and Winding Mills", 
        "Thread Mills", "Coated Fabrics, Not Rubberized", 
        "Tire Cord and Fabrics", 
        "Non-woven Fabrics", "Cordage and Twine", 
        "Textile goods, Not Elsewhere Classified", 
        "Men's and Boys' Suits, Coats, and Overcoats", 
        "Men's and Boys' Shirts, Except Work Shirts", 
        "Men's and Boys' Underwear and Nightwear", 
        "Men's and Boys' Neckwear", 
        "Men's and Boys' Separate Trousers and Slacks", 
        "Men's and Boys' Work Clothing", 
        "Men's and Boys' Clothing, Not Elsewhere Classified", 
        "Women's, Misses', and Juniors' Blouses and Shirts", 
        "Women's, Misses', and Juniors' Dresses", 
        "Women's, Misses', and Juniors' Suits, Skirts, and Coats", 
        "Women's, Misses', and Juniors' Outerwear, Not Elsewhere Classified", 
        "Women's, Misses', Children's, and Infants' Underwear and Nightwear", 
        "Brassieres, Girdles, and Allied Garments", 
        "Hats, Caps, and Millinery", 
        "Girls', Children's, and Infants' Dresses, Blouses, and Shirts", 
        "Girls', Children's, and Infants' Outerwear, Not Elsewhere Classified", 
        "Fur Goods", "Dress and Work Gloves, Except Knit and All-Leather", 
        "Robes and Dressing Gowns", 
        "Waterproof Outerwear", 
        "Leather and Sheep-Lined Clothing", 
        "Apparel belts", "Apparel and Accessories, Not Elsewhere Classified", 
        "Curtains and Draperies", 
        "House furnishing, Except Curtains and Draperies", 
        "Textile Bags", "Canvas and Related Products", 
        "Pleating, Decorative and Novelty Stitching, and Tucking for the Trade", 
        "Automotive Trimmings, Apparel Findings, and Related Products", 
        "Schiffli Machine Embroideries", 
        "Fabricated Textile Products, Not Elsewhere Classified", 
        "Logging", "Sawmills and Planing Mills, General", 
        "Hardwood Dimension and Flooring Mills", 
        "Special Product Sawmills, Not Elsewhere Classified", 
        "Millwork", "Wood Kitchen Cabinets", 
        "Hardwood Veneer and Plywood", 
        "Softwood Veneer and Plywood", 
        "Structural Wood Members, Not Elsewhere Classified", 
        "Nailed and Lock Corner Wood Boxes and Shook", 
        "Wood Pallets and Skids", 
        "Wood Containers, Not Elsewhere Classified", 
        "Mobile Homes", "Prefabricated Wood Buildings and Components", 
        "Wood Preserving", "Reconstituted Wood Products", 
        "Wood Products, Not Elsewhere Classified", 
        "Wood Household Furniture, Except Upholstered", 
        "Wood Household Furniture, Upholstered", 
        "Metal Household Furniture", 
        "Mattresses, Foundations, and Convertible Beds", 
        "Wood Television, Radio, Phonograph, and Sewing Machine Cabinets", 
        "Household Furniture, Not Elsewhere Classified", 
        "Wood Office Furniture", 
        "Office Furniture, Except Wood", 
        "Public Building and Related Furniture", 
        "Wood Office and Store Fixtures, Partitions, Shelving, and Lockers", 
        "Office and Store Fixtures, Partitions, Shelving, and Lockers, Except Wood", 
        "Drapery Hardware and Window Blinds and Shades", 
        "Furniture and Fixtures, Not Elsewhere Classified", 
        "Pulp Mills", "Paper Mills", 
        "Paperboard Mills", "Setup Paperboard Boxes", 
        "Corrugated and Solid Fiber Boxes", 
        "Fiber Cans, Tubes, Drums, and Similar Products", 
        "Sanitary Food Containers, Except Folding", 
        "Folding Paperboard Boxes, Including Sanitary", 
        "Packaging Paper and Plastics Film, Coated and Laminated", 
        "Coated and Laminated Paper, Not Elsewhere Classified", 
        "Plastics, Foil, and Coated Paper Bags", 
        "Uncoated Paper and Multiwall Bags", 
        "Die-Cut Paper and Paperboard and Cardboard", 
        "Sanitary Paper Products", 
        "Envelopes", "Stationery, Tablets, and Related Products", 
        "Converted Paper and Paperboard Products, Not Elsewhere Classified", 
        "Newspapers: Publishing, or Publishing and Printing", 
        "Periodicals: Publishing, or Publishing and Printing", 
        "Books: Publishing, or Publishing and Printing", 
        "Book Printing", "Miscellaneous Publishing", 
        "Commercial Printing, Lithographic", 
        "Commercial Printing, Gravure", 
        "Commercial Printing, Not Elsewhere Classified", 
        "Manifold Business Forms", 
        "Greeting Cards", "Blankbooks, Looseleaf Binders and Devices", 
        "Bookbinding and Related Work", 
        "Typesetting", "Platemaking and Related Services", 
        "Alkalies and Chlorine", 
        "Industrial Gases", "Inorganic Pigments", 
        "Industrial Inorganic Chemicals, Not Elsewhere Classified", 
        "Plastics Materials, Synthetic Resins, and Nonvulcanizable Elastomers", 
        "Synthetic Rubber (Vulcanizable Elastomers)", 
        "Cellulosic Manmade Fibers", 
        "Manmade Organic Fibers, Except Cellulosic", 
        "Medicinal Chemicals and Botanical Products", 
        "Pharmaceutical Preparations", 
        "In Vitro and In Vivo Diagnostic Substances", 
        "Biological Products, Except Diagnostic Substances", 
        "Soap and Other Detergents, Except Specialty Cleaners", 
        "Specialty Cleaning, Polishing, and Sanitation Preparations", 
        "Surface Active Agents, Finishing Agents, Sulfonated Oils, and Assistants", 
        "Perfumes, Cosmetics, and Other Toilet Preparations", 
        "Paints, Varnishes, Lacquers, Enamels, and Allied Products", 
        "Gum and Wood Chemicals", 
        "Cyclic Organic Crudes and Intermediates, and Organic Dyes and Pigments", 
        "Industrial Organic Chemicals, Not Elsewhere Classified", 
        "Nitrogenous Fertilizers", 
        "Phosphatic Fertilizers", 
        "Fertilizers, Mixing Only", 
        "Pesticides and Agricultural Chemicals, Not Elsewhere Classified", 
        "Adhesives and Sealants", 
        "Explosives", "Printing Ink", 
        "Carbon Black", "Chemicals and Chemical Preparations, Not Elsewhere Classified", 
        "Petroleum Refining", "Asphalt Paving Mixtures and Blocks", 
        "Asphalt Felts and Coatings", 
        "Lubricating Oils and Greases", 
        "Products of Petroleum and Coal, Not Elsewhere Classified", 
        "Tires and Inner Tubes", 
        "Rubber and Plastics Footwear", 
        "Rubber and Plastics Hose and Belting", 
        "Gaskets, Packing, and Sealing Devices", 
        "Molded, Extruded, and Lathe-Cut Mechanical Rubber Goods", 
        "Fabricated Rubber Products, Not Elsewhere Classified", 
        "Unsupported Plastics Film and Sheet", 
        "Unsupported Plastics Profile Shapes", 
        "Laminated Plastics Plate, Sheet, and Profile Shapes", 
        "Plastics Pipe", "Plastics Bottles", 
        "Plastics Foam Products", 
        "Custom Compounding of Purchased Plastics Resins", 
        "Plastics Plumbing Fixtures", 
        "Plastics Products, Not Elsewhere Classified", 
        "Leather Tanning and Finishing", 
        "Boot and Shoe Cut Stock and Findings", 
        "House Slippers", "Men's Footwear, Except Athletic", 
        "Women's Footwear, Except Athletic", 
        "Footwear, Except Rubber, Not Elsewhere Classified", 
        "Leather Gloves and Mittens", 
        "Luggage", "Women's Handbags and Purses", 
        "Personal Leather Goods, Except Women's Handbags and Purses", 
        "Leather Goods, Not Elsewhere Classified", 
        "Flat Glass", "Glass Containers", 
        "Pressed and Blown Glass and Glassware, Not Elsewhere Classified", 
        "Glass Products, Made of Purchased Glass", 
        "Cement, Hydraulic", "Brick and Structural Clay Tile", 
        "Ceramic Wall and Floor Tile", 
        "Clay Refractories", "Structural Clay Products, Not Elsewhere Classified", 
        "Vitreous China Plumbing Fixtures and China and Earthenware Fittings and Bathroom Accessories", 
        "Vitreous China Table and Kitchen Articles", 
        "Fine Earthenware (Whiteware) Table and Kitchen Articles", 
        "Porcelain Electrical Supplies", 
        "Pottery Products, Not Elsewhere Classified", 
        "Concrete Block and Brick", 
        "Concrete Products, Except Block and Brick", 
        "Ready-Mixed Concrete", 
        "Lime", "Description for 3275: Gypsum Products", 
        "Cut Stone and Stone Products", 
        "Abrasive Products", "Asbestos Products", 
        "Minerals and Earths, Ground or Otherwise Treated", 
        "Mineral Wool", "Nonclay Refractories", 
        "Nonmetallic Mineral Products, Not Elsewhere Classified", 
        "Steel Works, Blast Furnaces (Including Coke Ovens), and Rolling Mills", 
        "Electrometallurgical Products, Except Steel", 
        "Steel Wiredrawing and Steel Nails and Spikes", 
        "Cold-Rolled Steel Sheet, Strip, and Bars", 
        "Steel Pipe and Tubes", 
        "Gray and Ductile Iron Foundries", 
        "Malleable Iron Foundries", 
        "Steel Investment Foundries", 
        "Steel Foundries, Not Elsewhere Classified", 
        "Primary Smelting and Refining of Copper", 
        "Primary Production of Aluminum", 
        "Primary Smelting and Refining of Nonferrous Metals, Except Copper and Aluminum", 
        "Secondary Smelting and Refining of Nonferrous Metals", 
        "Rolling, Drawing, and Extruding Of Copper", 
        "Aluminum Sheet, Plate, and Foil", 
        "Aluminum Extruded Products", 
        "Aluminum Rolling and Drawing, Not Elsewhere Classified", 
        "Rolling, Drawing, and Extruding of Nonferrous Metals, Except Copper and Aluminum", 
        "Drawing and Insulating of Nonferrous Wire", 
        "Aluminum Die-Castings", 
        "Nonferrous Die-Castings, Except Aluminum", 
        "Aluminum Foundries", "Copper Foundries", 
        "Nonferrous Foundries, Except Aluminum and Copper", 
        "Metal Heat Treating", 
        "Primary Metal Products, Not Elsewhere Classified", 
        "Metal Cans", "Metal Shipping Barrels, Drums, Kegs, and Pails", 
        "Cutlery", "Hand and Edge Tools, Except Machine Tools and Handsaws", 
        "Saw Blades and Handsaws", 
        "Hardware, Not Elsewhere Classified", 
        "Enameled Iron and Metal Sanitary Ware", 
        "Plumbing Fixture Fittings and Trim", 
        "Heating Equipment, Except Electric and Warm Air Furnaces", 
        "Fabricated Structural Metal", 
        "Metal Doors, Sash, Frames, Molding, and Trim Manufacturing", 
        "Fabricated Plate Work (Boiler Shops)", 
        "Sheet Metal Work", "Architectural and Ornamental Metal Work", 
        "Prefabricated Metal Buildings and Components", 
        "Miscellaneous Structural Metal Work", 
        "Screw Machine Products", 
        "Bolts, Nuts, Screws, Rivets, and Washers", 
        "Iron and Steel Forgings", 
        "Nonferrous Forgings", 
        "Automotive Stampings", 
        "Crowns and Closures", 
        "Metal Stampings, Not Elsewhere Classified", 
        "Electroplating, Plating, Polishing, Anodizing, and Coloring", 
        "Coating, Engraving, and Allied Services, Not Elsewhere Classified", 
        "Small Arms Ammunition", 
        "Ammunition, Except for Small Arms", 
        "Small Arms", "Ordnance and Accessories, Not Elsewhere Classified", 
        "Industrial Valves", "Fluid Power Valves and Hose Fittings", 
        "Steel Springs, Except Wire", 
        "Valves and Pipe Fittings, Not Elsewhere Classified", 
        "Wire Springs", "Miscellaneous Fabricated Wire Products", 
        "Metal Foil and Leaf", 
        "Fabricated Pipe and Pipe Fittings", 
        "Fabricated Metal Products, Not Elsewhere Classified", 
        "Steam, Gas, and Hydraulic Turbines, and Turbine Generator Set Units", 
        "Internal Combustion Engines, Not Elsewhere Classified", 
        "Farm Machinery and Equipment", 
        "Lawn and Garden Tractors and Home Lawn and Garden Equipment", 
        "Construction Machinery and Equipment", 
        "Mining Machinery and Equipment, Except Oil and Gas Field Machinery and Equipment", 
        "Oil and Gas Field Machinery and Equipment", 
        "Elevators and Moving Stairways", 
        "Conveyors and Conveying Equipment", 
        "Overhead Traveling Cranes, Hoists, and Monorail Systems", 
        "Industrial Trucks, Tractors, Trailers, and Stackers", 
        "Machine Tools, Metal Cutting Types", 
        "Machine Tools, Metal Forming Types", 
        "Industrial Patterns", 
        "Special Dies and Tools, Die Sets, Jigs and Fixtures, and Industrial Molds", 
        "Cutting Tools, Machine Tool Accessories, and Machinists' Precision Measuring Devices", 
        "Power-Driven Handtools", 
        "Rolling Mill Machinery and Equipment", 
        "Electric and Gas Welding and Soldering Equipment", 
        "Metalworking Machinery, Not Elsewhere Classified", 
        "Textile Machinery", "Woodworking Machinery", 
        "Paper Industries Machinery", 
        "Printing Trades Machinery and Equipment", 
        "Food Products Machinery", 
        "Special Industry Machinery, Not Elsewhere Classified", 
        "Pumps and Pumping Equipment", 
        "Ball and Roller Bearings", 
        "Air and Gas Compressors", 
        "Industrial and Commercial Fans and Blowers and Air Purification Equipment", 
        "Packaging Machinery", 
        "Speed Changers, Industrial High-Speed Drives, and Gears", 
        "Industrial Process Furnaces and Ovens", 
        "Mechanical Power Transmission Equipment, Not Elsewhere Classified", 
        "General Industrial Machinery and Equipment, Not Elsewhere", 
        "Electronic Computers", 
        "Computer Storage Devices", 
        "Computer Terminals", "Computer Peripheral Equipment, Not Elsewhere Classified", 
        "Calculating and Accounting Machines, Except Electronic Computers", 
        "Office Machines, Not Elsewhere Classified", 
        "Automatic Vending Machines", 
        "Commercial Laundry, Drycleaning, and Pressing Machines", 
        "Air-Conditioning and Warm Air Heating Equipment and Commercial and Industrial Refrigeration Equipment", 
        "Measuring and Dispensing Pumps", 
        "Service Industry Machinery, Not Elsewhere Classified", 
        "Carburetors, Pistons, Piston Rings, and Valves", 
        "Fluid Power Cylinders and Actuators", 
        "Fluid Power Pumps and Motors", 
        "Scales and Balances, Except Laboratory", 
        "Industrial and Commercial Machinery and Equipment, Not Elsewhere Classified", 
        "Power, Distribution, and Specialty Transformers", 
        "Switchgear and Switchboard Apparatus", 
        "Motors and Generators", 
        "Carbon and Graphite Products", 
        "Relays and Industrial Controls", 
        "Electrical Industrial Apparatus, Not Elsewhere Classified", 
        "Household Cooking Equipment", 
        "Household Refrigerators and Home and Farm Freezers", 
        "Household Laundry Equipment", 
        "Electric Housewares and Fans", 
        "Household Vacuum Cleaners", 
        "Household Appliances, Not Elsewhere Classified", 
        "Electric Lamp Bulbs and Tubes", 
        "Current-Carrying Wiring Devices", 
        "Noncurrent-Carrying Wiring Devices", 
        "Residential Electric Lighting Fixtures", 
        "Commercial, Industrial, and Institutional Electric Lighting Fixtures", 
        "Vehicular Lighting Equipment", 
        "Lighting Equipment, Not Elsewhere Classified", 
        "Household Audio and Video Equipment", 
        "Phonograph Records and Prerecorded Audio Tapes and Disks", 
        "Telephone and Telegraph Apparatus", 
        "Radio and Television Broadcasting and Communications Equipment", 
        "Communications Equipment, Not Elsewhere Classified", 
        "Electron Tubes", "Printed Circuit Boards", 
        "Semiconductors and Related Devices", 
        "Electronic Capacitors", 
        "Electronic Resistors", 
        "Electronic Coils, Transformers, and Other Inductors", 
        "Electronic Connectors", 
        "Electronic Components, Not Elsewhere Classified", 
        "Storage Batteries", "Primary Batteries, Dry and Wet", 
        "Electrical Equipment for Internal Combustion Engines", 
        "Magnetic And Optical Recording Media", 
        "Electrical Machinery, Equipment, and Supplies, Not Elsewhere", 
        "Motor Vehicles and Passenger Car Bodies", 
        "Truck and Bus Bodies", 
        "Motor Vehicle Parts and Accessories", 
        "Truck Trailers", "Motor Homes", 
        "Aircraft", "Aircraft Engines and Engine Parts", 
        "Aircraft Parts and Auxiliary Equipment, Not Elsewhere Classified", 
        "Ship Building and Repairing", 
        "Boat Building and Repairing", 
        "Railroad Equipment", "Motorcycles, Bicycles, and Parts", 
        "Guided Missiles and Space Vehicles", 
        "Guided Missile and Space Vehicle Propulsion Units and Propulsion Unit Parts", 
        "Guided Missile Space Vehicle Parts and Auxiliary Equipment, Not Elsewhere Classified", 
        "Travel Trailers and Campers", 
        "Tanks and Tank Components", 
        "Transportation Equipment, Not Elsewhere Classified", 
        "Search, Detection, Navigation, Guidance, Aeronautical, and Nautical Systems and Instruments", 
        "Laboratory Apparatus and Furniture", 
        "Automatic Controls for Regulating Residential and Commercial Environments and Appliances", 
        "Industrial Instruments for Measurement, Display, and Control of Process Variables; and Related Products", 
        "Totalizing Fluid Meters and Counting Devices", 
        "Instruments for Measuring and Testing of Electricity and Electrical Signals", 
        "Laboratory Analytical Instruments", 
        "Optical Instruments and Lenses", 
        "Measuring and Controlling Devices, Not Elsewhere Classified", 
        "Surgical and Medical Instruments and Apparatus", 
        "Orthopedic, Prosthetic, and Surgical Appliances and Supplies", 
        "Dental Equipment and Supplies", 
        "X-Ray Apparatus and Tubes and Related Irradiation Apparatus", 
        "Electromedical and Electrotherapeutic Apparatus", 
        "Ophthalmic Goods", "Photographic Equipment and Supplies", 
        "Watches, Clocks, Clockwork Operated Devices, and Parts", 
        "Jewelry, Precious Metal", 
        "Silverware, Plated Ware, and Stainless Steel Ware", 
        "Jewelers' Findings and Materials, and Lapidary Work", 
        "Musical Instruments", 
        "Dolls and Stuffed Toys", 
        "Games, Toys, and Children's Vehicles, Except Dolls and Bicycles", 
        "Sporting and Athletic Goods, Not Elsewhere Classified", 
        "Pens, Mechanical Pencils, and Parts", 
        "Lead Pencils, Crayons, and Artists' Materials", 
        "Marking Devices", "Carbon Paper and Inked Ribbons", 
        "Costume Jewelry and Costume Novelties, Except Precious Metal", 
        "Fasteners, Buttons, Needles, and Pins", 
        "Brooms and Brushes", "Signs and Advertising Specialties", 
        "Burial Caskets", "Linoleum, Asphalted-Felt-Base, and Other Hard Surface Floor Coverings, Not Elsewhere Classified", 
        "Manufacturing Industries, Not Elsewhere Classified", 
        "Railroads, Line-Haul Operating", 
        "Railroad Switching and Terminal Establishments", 
        "Local and Suburban Transit", 
        "Local Passenger Transportation, Not Elsewhere Classified", 
        "Taxicabs", "Intercity and Rural Bus Transportation", 
        "Local Bus Charter Service", 
        "Bus Charter Service, Except Local", 
        "School Buses", "Terminal and Service Facilities for Motor Vehicle Passenger Transportation", 
        "Local Trucking Without Storage", 
        "Trucking, Except Local", 
        "Local Trucking With Storage", 
        "Courier Services, Except by Air", 
        "Farm Product Warehousing and Storage", 
        "Refrigerated Warehousing and Storage", 
        "General Warehousing and Storage", 
        "Special Warehousing and Storage, Not Elsewhere Classified", 
        "Terminal and Joint Terminal Maintenance Facilities for Motor Freight Transportation", 
        "United States Postal Service", 
        "Deep Sea Foreign Transportation of Freight", 
        "Deep Sea Domestic Transportation of Freight", 
        "Freight Transportation on the Great Lakes-St. Lawrence Seaway", 
        "Water Transportation of Freight, Not Elsewhere Classified", 
        "Deep Sea Transportation of Passengers, Except by Ferry", 
        "Ferries", "Water Transportation of Passengers, Not Elsewhere Classified", 
        "Marine Cargo Handling", 
        "Towing and Tugboat Services", 
        "Marinas", "Water Transportation Services, Not Elsewhere Classified", 
        "Air Transportation, Scheduled", 
        "Air Courier Services", 
        "Air Transportation, Nonscheduled", 
        "Airports, Flying Fields, and Airport Terminal Services", 
        "Crude Petroleum Pipelines", 
        "Refined Petroleum Pipelines", 
        "Pipelines, Not Elsewhere Classified", 
        "Travel Agencies", "Tour Operators", 
        "Arrangement of Passenger Transportation, Not Elsewhere Classified", 
        "Arrangement of Transportation of Freight and Cargo", 
        "Rental of Railroad Cars", 
        "Packing and Crating", 
        "Fixed Facilities and Inspection and Weighing Services for Motor Vehicle Transportation", 
        "Transportation Services, Not Elsewhere Classified", 
        "Radiotelephone Communications", 
        "Telephone Communications, Except Radiotelephone", 
        "Telegraph and Other Message Communications", 
        "Radio Broadcasting Stations", 
        "Television Broadcasting Stations", 
        "Cable and Other Pay Television Services", 
        "Communications Services, Not Elsewhere Classified", 
        "Electric Services", "Natural Gas Transmission", 
        "Natural Gas Transmission and Distribution", 
        "Natural Gas Distribution", 
        "Mixed, Manufactured, or Liquefied Petroleum Gas Production and/or", 
        "Electric and Other Services Combined", 
        "Gas and Other Services Combined", 
        "Combination Utilities, Not Elsewhere Classified", 
        "Water Supply", "Sewerage Systems", 
        "Refuse Systems", "Sanitary Services, Not Elsewhere Classified", 
        "Steam and Air-Conditioning Supply", 
        "Irrigation Systems", "Automobiles and Other Motor Vehicles", 
        "Motor Vehicle Supplies and New Parts", 
        "Tires and Tubes", "Motor Vehicle Parts, Used", 
        "Furniture", "Home furnishings", 
        "Lumber, Plywood, Millwork, and Wood Panels", 
        "Brick, Stone, and Related Construction Materials", 
        "Roofing, Siding, and Insulation Materials", 
        "Construction Materials, Not Elsewhere Classified", 
        "Photographic Equipment and Supplies", 
        "Office Equipment", "Computers and Computer Peripheral Equipment and Software", 
        "Commercial Equipment, Not Elsewhere Classified", 
        "Medical, Dental, and Hospital Equipment and Supplies", 
        "Ophthalmic Goods", "Professional Equipment and Supplies, Not Elsewhere Classified", 
        "Metals Service Centers and Offices", 
        "Coal and Other Minerals and Ores", 
        "Electrical Apparatus and Equipment Wiring Supplies, and Construction Materials", 
        "Electrical Appliances, Television and Radio Sets", 
        "Electronic Parts and Equipment, Not Elsewhere Classified", 
        "Hardware", "Plumbing and Heating Equipment and Supplies (Hydronics)", 
        "Warm Air Heating and Air-Conditioning Equipment and Supplies", 
        "Refrigeration Equipment and Supplies", 
        "Construction and Mining (Except Petroleum) Machinery and Equipment", 
        "Farm and Garden Machinery and Equipment", 
        "Industrial Machinery and Equipment", 
        "Industrial Supplies", 
        "Service Establishment Equipment and Supplies", 
        "Transportation Equipment and Supplies, Except Motor Vehicles", 
        "Sporting and Recreational Goods and Supplies", 
        "Toys and Hobby Goods and Supplies", 
        "Scrap and Waste Materials", 
        "Jewelry, Watches, Precious Stones, and Precious Metals", 
        "Durable Goods, Not Elsewhere Classified", 
        "Printing and Writing Paper", 
        "Stationery and Office Supplies", 
        "Industrial and Personal Service Paper", 
        "Drugs, Drug Proprietaries, and Druggists' Sundries", 
        "Piece Goods, Notions, and Other Dry Good", 
        "Men's and Boy's Clothing and Furnishings", 
        "Women's, Children's, and Infants' Clothing and Accessories", 
        "Footwear", "Groceries, General Line", 
        "Packaged Frozen Foods", 
        "Dairy Products, Except Dried or Canned", 
        "Poultry and Poultry Products", 
        "Confectionery", "Fish and Seafoods", 
        "Meats and Meat Products", 
        "Fresh Fruits and Vegetables", 
        "Groceries and Related Products, Not Elsewhere Classified", 
        "Grain and Field Beans", 
        "Livestock", "Farm-Product Raw Materials, Not Elsewhere Classified", 
        "Plastics Materials and Basic Forms and Shapes", 
        "Chemicals and Allied Products, Not Elsewhere Classified", 
        "Petroleum Bulk stations and Terminals", 
        "Petroleum and Petroleum Products Wholesalers, Except Bulk Stations and Terminals", 
        "Beer and Ale", "Wine and Distilled Alcoholic Beverages", 
        "Farm Supplies", "Books, Periodicals, and Newspapers", 
        "Flowers, Nursery Stock, and Florists' Supplies", 
        "Tobacco and Tobacco Products", 
        "Paints, Varnishes, and Supplies", 
        "Nondurable Goods, Not Elsewhere Classified", 
        "Lumber and Other Building Materials Dealers", 
        "Paint, Glass, and Wallpaper Stores", 
        "Hardware Stores", "Retail Nurseries, Lawn and Garden Supply Stores", 
        "Mobile Home Dealers", 
        "Department Stores", "Variety Stores", 
        "Miscellaneous General Merchandise Stores", 
        "Grocery Stores", "Meat and Fish (Seafood) Markets, Including Freezer Provisioners", 
        "Fruit and Vegetable Markets", 
        "Candy, Nut, and Confectionery Stores", 
        "Dairy Products Stores", 
        "Retail Bakeries", "Miscellaneous Food Stores", 
        "Motor Vehicle Dealers (New and Used)", 
        "Motor Vehicle Dealers (Used Only)", 
        "Auto and Home Supply Stores", 
        "Gasoline Service Stations", 
        "Boat Dealers", "Recreational Vehicle Dealers", 
        "Motorcycle Dealers", "Automotive Dealers, Not Elsewhere Classified", 
        "Men's and Boys' Clothing and Accessory Stores", 
        "Women's Clothing Stores", 
        "Women's Accessory and Specialty Stores", 
        "Children's and Infants' Wear Stores", 
        "Family Clothing Stores", 
        "Shoe Stores", "Miscellaneous Apparel and Accessory Stores", 
        "Furniture Stores", "Floor Covering Stores", 
        "Drapery, Curtain, and Upholstery Stores", 
        "Miscellaneous home furnishings Stores", 
        "Household Appliance Stores", 
        "Radio, Television, and Consumer Electronics Stores", 
        "Computer and Computer Software Stores", 
        "Record and Prerecorded Tape Stores", 
        "Musical Instrument Stores", 
        "Eating Places", "Drinking Places (alcoholic Beverages)", 
        "Drug Stores and Proprietary Stores", 
        "Liquor Stores", "Used Merchandise Stores", 
        "Sporting Goods Stores and Bicycle Shops", 
        "Book Stores", "Stationery Stores", 
        "Jewelry Stores", "Hobby, Toy, and Game Shops", 
        "Camera and Photographic Supply Stores", 
        "Gift, Novelty, and Souvenir Shops", 
        "Luggage and Leather Goods Stores", 
        "Sewing, Needlework, and Piece Goods Stores", 
        "Catalog and Mail-Order Houses", 
        "Automatic Merchandising Machine Operators", 
        "Direct Selling Establishments", 
        "Fuel Oil Dealers", "Liquefied Petroleum Gas (Bottled Gas) Dealers", 
        "Fuel Dealers, Not Elsewhere Classified", 
        "Florists", "Tobacco Stores and Stands", 
        "News Dealers and Newsstands", 
        "Optical Goods Stores", 
        "Miscellaneous Retail Stores, Not Elsewhere Classified", 
        "Federal Reserve Banks", 
        "Central Reserve Depository Institutions, Not Elsewhere Classified", 
        "National Commercial Banks", 
        "State Commercial Banks", 
        "Commercial Banks, Not Elsewhere Classified", 
        "Savings Institutions, Federally Chartered", 
        "Savings Institutions, Not Federally Chartered", 
        "Credit Unions, Federally Chartered", 
        "Credit Unions, Not Federally Chartered", 
        "Branches and Agencies of Foreign Banks", 
        "Foreign Trade and International Banking Institutions", 
        "Non-deposit Trust Facilities,", 
        "Functions Related to Depository Banking, Not Elsewhere Classified", 
        "Federal and Federally-Sponsored Credit Agencies", 
        "Personal Credit Institutions", 
        "Short-Term Business Credit Institutions, Except Agricultural", 
        "Miscellaneous business Credit Institutions", 
        "Mortgage Bankers and Loan Correspondents", 
        "Loan Brokers", "Security Brokers, Dealers, and Flotation Companies", 
        "Commodity Contracts Brokers and Dealers", 
        "Security and Commodity Exchanges", 
        "Investment Advice", "Services Allied With the Exchange of Securities or Commodities, Not Elsewhere Classified", 
        "Life Insurance", "Accident and Health Insurance", 
        "Hospital and Medical Service Plans", 
        "Fire, Marine, and Casualty Insurance", 
        "Surety Insurance", "Title Insurance", 
        "Pension, Health, and Welfare Funds", 
        "Insurance Carriers, Not Elsewhere Classified", 
        "Insurance Agents, Brokers, and Service", 
        "Operators of Nonresidential Buildings", 
        "Operators of Apartment Buildings", 
        "Operators of Dwellings Other Than Apartment Buildings", 
        "Operators of Residential Mobile Home Sites", 
        "Lessors of Railroad Property", 
        "Lessors of Real Property, Not Elsewhere Classified", 
        "Real Estate Agents and Managers", 
        "Title Abstract Offices", 
        "Land Subdividers and Developers, Except Cemeteries", 
        "Cemetery Subdividers and Developers", 
        "Offices of Bank Holding Companies", 
        "Offices of Holding Companies, Not Elsewhere Classified", 
        "Management Investment Offices, Open-End", 
        "Unit Investment Trusts, Face-Amount Certificate Offices, and Closed-End Management Investment Offices", 
        "Educational, Religious, and Charitable Trusts", 
        "Trusts, Except Educational, Religious, and Charitable", 
        "Oil Royalty Traders", 
        "Patent Owners and Lessors", 
        "Real Estate Investment Trusts", 
        "Investors, Not Elsewhere Classified", 
        "Hotels and Motels", "Rooming and Boarding Houses", 
        "Sporting and Recreational Camps", 
        "Recreational Vehicle Parks and Campsites", 
        "Organization Hotels and Lodging Houses, on Membership Basis", 
        "Power Laundries, Family and Commercial", 
        "Garment Pressing, and Agents for Laundries and Drycleaners", 
        "Linen Supply", "Coin-Operated Laundries and Drycleaning", 
        "Drycleaning Plants, Except Rug Cleaning", 
        "Carpet and Upholstery Cleaning", 
        "Industrial Launderers", 
        "Laundry and Garment Services, Not Elsewhere Classified", 
        "Photographic Studios, Portrait", 
        "Beauty Shops", "Barber Shops", 
        "Shoe Repair Shops and Shoeshine Parlors", 
        "Funeral Service and Crematories", 
        "Tax Return Preparation Services", 
        "Miscellaneous Personal Services, Not Elsewhere Classified", 
        "Advertising Agencies", 
        "Outdoor Advertising Services", 
        "Radio, Television, and Publishers' Advertising Representatives", 
        "Advertising, Not Elsewhere Classified", 
        "Adjustment and Collection Services", 
        "Credit Reporting Services", 
        "Direct Mail Advertising Services", 
        "Photocopying and Duplicating Services", 
        "Commercial Photography", 
        "Commercial Art and Graphic Design", 
        "Secretarial and Court Reporting Services", 
        "Disinfecting and Pest Control Services", 
        "Building Cleaning and Maintenance Services, Not Elsewhere", 
        "Medical Equipment Rental and Leasing", 
        "Heavy Construction Equipment Rental and Leasing", 
        "Equipment Rental and Leasing, Not Elsewhere Classified", 
        "Employment Agencies", 
        "Help Supply Services", 
        "Computer Programming Services", 
        "Prepackaged Software", 
        "Computer Integrated Systems Design", 
        "Computer Processing and Data Preparation and Processing Services", 
        "Information Retrieval Services", 
        "Computer Facilities Management Services", 
        "Computer Rental and Leasing", 
        "Computer Maintenance and Repair", 
        "Computer Related Services, Not Elsewhere Classified", 
        "Detective, Guard, and Armored Car Services", 
        "Security Systems Services", 
        "News Syndicates", "Photofinishing Laboratories", 
        "Business Services, Not Elsewhere Classified", 
        "Truck Rental and Leasing, Without Drivers", 
        "Passenger Car Rental", 
        "Passenger Car Leasing", 
        "Utility Trailer and Recreational Vehicle Rental", 
        "Automobile Parking", "Top, Body, and Upholstery Repair Shops and Paint Shops", 
        "Automotive Exhaust System Repair Shops", 
        "Tire Retreading and Repair Shops", 
        "Automotive Glass Replacement Shops", 
        "Automotive Transmission Repair Shops", 
        "General Automotive Repair Shops", 
        "Automotive Repair Shops, Not Elsewhere Classified", 
        "Carwashes", "Automotive Services, Except Repair and Carwashes", 
        "Radio and Television Repair Shops", 
        "Refrigeration and Air-Conditioning Service and Repair Shops", 
        "Electrical and Electronic Repair Shops, Not Elsewhere Classified", 
        "Watch, Clock, and Jewelry Repair", 
        "Reupholstery and Furniture Repair", 
        "Welding Repair", "Armature Rewinding Shops", 
        "Repair Shops and Related Services, Not Elsewhere Classified", 
        "Motion Picture and Video Tape Production", 
        "Services Allied to Motion Picture Production", 
        "Motion Picture and Video Tape Distribution", 
        "Services Allied to Motion Picture Distribution", 
        "Motion Picture Theaters, Except Drive-In", 
        "Drive-In Motion Picture Theaters", 
        "Video Tape Rental", "Dance Studios, Schools, and Halls", 
        "Theatrical Producers (Except Motion Picture) and Miscellaneous Theatrical Services", 
        "Bands, Orchestras, Actors, and Other Entertainers and Entertainment Groups", 
        "Bowling Centers", "Professional Sports Clubs and Promoters", 
        "Racing, Including Track Operation", 
        "Physical Fitness Facilities", 
        "Public Golf Courses", 
        "Coin-Operated Amusement Devices", 
        "Amusement Parks", "Membership Sports and Recreation Clubs", 
        "Amusement and Recreation Services, Not Elsewhere Classified", 
        "Offices and Clinics of Doctors of Medicine", 
        "Offices and Clinics of Dentists", 
        "Offices and Clinics of Doctors of Osteopathy", 
        "Offices and Clinics of Chiropractors", 
        "Offices and Clinics of Optometrists", 
        "Offices and Clinics of Podiatrists", 
        "Offices and Clinics of Health Practitioners, Not Elsewhere Classified", 
        "Skilled Nursing Care Facilities", 
        "Intermediate Care Facilities", 
        "Nursing and Personal Care Facilities, Not Elsewhere Classified", 
        "General Medical and Surgical Hospitals", 
        "Psychiatric Hospitals", 
        "Specialty Hospitals, Except Psychiatric", 
        "Medical Laboratories", 
        "Dental Laboratories", 
        "Home Health Care Services", 
        "Kidney Dialysis Centers", 
        "Specialty Outpatient Facilities, Not Elsewhere Classified", 
        "Health and Allied Services, Not Elsewhere Classified", 
        "Legal Services", "Elementary and Secondary Schools", 
        "Colleges, Universities, and Professional Schools", 
        "Junior Colleges and Technical Institutes", 
        "Libraries", "Data Processing Schools", 
        "Business and Secretarial Schools", 
        "Vocational Schools, Not Elsewhere Classified", 
        "Schools and Educational Services, Not Elsewhere Classified", 
        "Individual and Family Social Services", 
        "Job Training and Vocational Rehabilitation Services", 
        "Child Day Care Services", 
        "Residential Care", "Social Services, Not Elsewhere Classified", 
        "Museums and Art Galleries", 
        "Arboreta and Botanical or Zoological Gardens", 
        "Business Associations", 
        "Professional Membership Organizations", 
        "Labor Unions and Similar Labor Organizations", 
        "Civic, Social, and Fraternal Associations", 
        "Political Organizations", 
        "Religious Organizations", 
        "Membership Organizations, Not Elsewhere Classified", 
        "Engineering Services", 
        "Architectural Services", 
        "Surveying Services", "Accounting, Auditing, and Bookkeeping Services", 
        "Commercial Physical and Biological Research", 
        "Commercial Economic, Sociological, and Educational Research", 
        "Noncommercial Research Organizations", 
        "Testing Laboratories", 
        "Management Services", 
        "Management Consulting Services", 
        "Public Relations Services", 
        "Facilities Support Management Services", 
        "Business Consulting Services, Not Elsewhere Classified", 
        "Private Households", "Services, Not Elsewhere Classified", 
        "Executive Offices", "Legislative Bodies", 
        "Executive and Legislative Offices Combined", 
        "General Government, Not Elsewhere Classified", 
        "Courts", "Police Protection", 
        "Legal Counsel and Prosecution", 
        "Correctional Institutions", 
        "Fire Protection", "Public Order and Safety, Not Elsewhere Classified", 
        "Public Finance, Taxation, and Monetary Policy", 
        "Administration of Educational Programs", 
        "Administration of Public Health Programs", 
        "Administration of Social, Human Resource and Income Maintenance Programs", 
        "Administration of Veterans' Affairs, Except Health and Insurance", 
        "Air and Water Resource and Solid Waste Management", 
        "Land, Mineral, Wildlife, and Forest Conservation", 
        "Administration of Housing Programs", 
        "Administration of Urban Planning and Community and Rural Development", 
        "Administration of General Economic Programs", 
        "Regulation and Administration of Transportation Programs", 
        "Regulation and Administration of Communications, Electric, Gas, and Other Utilities", 
        "Regulation of Agricultural Marketing and Commodities", 
        "Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors", 
        "Space and Research and Technology", 
        "National Security", "International Affairs", 
        "Nonclassifiable Establishments")), 
    row.names = c(NA, -1005L), 
    class = "data.frame")
